print(gpio.read(0))
print(gpio.read(1))
print(gpio.read(2))
print(gpio.read(3))
print(gpio.read(4))
print(gpio.read(5))
print(gpio.read(6))
print(gpio.read(7))
print(gpio.read(8))
print(gpio.read(9))
print(gpio.read(10))
print(gpio.read(11))
print(gpio.read(12))

